# Inherit style from another configuration
inherit_from: .rubocop_todo.yml

# Apply rule to all cops
AllCops:
  TargetRubyVersion: 1.9
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/schema.rb'
    - 'vendor/bundle/**/*'
    - 'bundle/**/*'
    - 'config/**/*'
    - 'bin/*'

Bundler/OrderedGems:
  Enabled: true

Layout/AlignArray:
  Enabled: true

Layout/AlignHash:
  Enabled: true

Layout/AlignParameters:
  Enabled: true

Layout/BlockEndNewline:
  Enabled: true

Layout/CommentIndentation:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Layout/EmptyLinesAroundBlockBody:
  Enabled: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: true

Layout/ExtraSpacing:
  Enabled: true

Layout/FirstParameterIndentation:
  Enabled: true

Layout/IndentArray:
  Enabled: true

Layout/IndentHash:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineBlockLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBrackets:
  Enabled: true

Layout/SpaceInsideParens:
  Enabled: true

Layout/Tab:
  Enabled: true

Layout/TrailingBlankLines:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/EndAlignment:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Style/AndOr:
  Enabled: true

Style/BarePercentLiterals:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/ClassCheck:
  Enabled: true

Style/ColonMethodCall:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/IfUnlessModifier:
  Enabled: true

Style/InverseMethods:
  Enabled: true

Style/MutableConstant:
  Enabled: true

Style/NegatedIf:
  Enabled: true

Style/Not:
  Enabled: true

Style/NumericPredicate:
  Enabled: true

Style/PercentLiteralDelimiters:
  Enabled: true

Style/PreferredHashMethods:
  Enabled: true

Style/Proc:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/RescueModifier:
  Enabled: true

Style/SafeNavigation:
  Enabled: true

Style/SingleLineMethods:
  Enabled: true

Style/SymbolProc:
  Enabled: true

Style/TrailingCommaInLiteral:
  Enabled: true

Lint/EndAlignment:
  Enabled: true

Style/NumericPredicate:
  Enabled: true

Style/SpecialGlobalVars:
  Enabled: true

Style/SymbolArray:
  Enabled: true
